name: 'mailchimp'
version: '0.0.1'

profile: 'default'

require-dbt-version: [">=0.16.0", "<0.17.0"]

models:
    mailchimp:
        materialized: table
        base:
            materialized: ephemeral
        intermediate:
            materialized: ephemeral
